-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_DATA_RE AS (
    SELECT ID, 1 AS LEVEL 
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL

    SELECT e.ID, er.LEVEL+1 AS LEVEL
    FROM ECOLI_DATA e
    INNER JOIN ECOLI_DATA_RE er
    ON e.PARENT_ID = er.ID
)
SELECT ID
FROM ECOLI_DATA_RE
WHERE LEVEL = 3
ORDER BY ID