-- 코드를 입력하세요
WITH OFFLINE AS (
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
),
ONLINE AS (
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
)



SELECT *
FROM ONLINE
WHERE SALES_DATE BETWEEN '2022-03-01' and '2022-03-31' 
UNION
SELECT *
FROM OFFLINE
WHERE SALES_DATE BETWEEN '2022-03-01' and '2022-03-31' 
ORDER BY 1, 2, 3