-- 코드를 작성해주세요
WITH RANKDATA AS (
    SELECT *,  
    NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENT
    FROM ECOLI_DATA
)

SELECT ID, 
    CASE 
        WHEN PERCENT = 1 THEN 'CRITICAL'
        WHEN PERCENT = 2 THEN 'HIGH'
        WHEN PERCENT = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM RANKDATA
ORDER BY ID