-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT, FISH_NAME
FROM
(
    SELECT FISH_NAME
    FROM 
    FISH_NAME_INFO n
    INNER JOIN
    FISH_INFO i
    ON i.FISH_TYPE = n.FISH_TYPE
) a
GROUP BY FISH_NAME
ORDER BY FISH_COUNT DESC

