-- 코드를 입력하세요
SELECT YEAR(s.SALES_DATE) AS YEAR, MONTH(s.SALES_DATE) AS MONTH, COUNT(DISTINCT s.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT s.USER_ID)/SUM(COUNT(DISTINCT s.USER_ID)) OVER(),1) AS PUCHASED_RATIO
FROM USER_INFO i
INNER JOIN ONLINE_SALE s
ON i.USER_ID = s.USER_ID
WHERE YEAR(i.JOINED) = 2021
GROUP BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE)
ORDER BY YEAR, MONTH