-- 코드를 작성해주세요
WITH RECURSIVE ECO_RE AS (
    
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
        
    UNION ALL
    
    SELECT e.ID, er.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA e
    INNER JOIN
    ECO_RE er
    ON e.PARENT_ID = er.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM
(
    SELECT er.ID, er.GENERATION
    FROM ECO_RE er
    LEFT JOIN ECOLI_DATA e
    ON e.PARENT_ID = er.ID
    WHERE e.PARENT_ID IS NULL
) a
GROUP BY GENERATION