-- 코드를 입력하세요

SELECT p.PRODUCT_ID, PRODUCT_NAME, PRICE * TOTAL_AMOUNT AS TOTAL_SALES
FROM 
FOOD_PRODUCT p
INNER JOIN 
(
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31' 
    GROUP BY PRODUCT_ID
) o
ON p.PRODUCT_ID = o.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID