-- 코드를 입력하세요
SELECT HISTORY_ID,
    FLOOR((DATEDIFF(END_DATE, START_DATE)+1)*
     DAILY_FEE*
        ((100-
        IFNULL((SELECT DISCOUNT_RATE
          FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
          WHERE p.CAR_TYPE = c.CAR_TYPE AND
          CASE 
              WHEN DATEDIFF(h.END_DATE, h.START_DATE)+1 >= 90 THEN p.DURATION_TYPE LIKE('90%')
              WHEN DATEDIFF(h.END_DATE, h.START_DATE)+1 >= 30 THEN p.DURATION_TYPE LIKE('30%')
              WHEN DATEDIFF(h.END_DATE, h.START_DATE)+1 >= 7 THEN p.DURATION_TYPE LIKE('7%')
          END), 0))/100)) AS FEE
 
FROM CAR_RENTAL_COMPANY_CAR c
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON c.CAR_ID = h.CAR_ID
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC


# SELECT *, DATEDIFF(END_DATE, START_DATE)+1
# FROM CAR_RENTAL_COMPANY_CAR c
# INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
# ON c.CAR_ID = h.CAR_ID
