-- 코드를 입력하세요

SELECT FLAVOR
FROM 
(
    SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF f
    UNION ALL
    (
        SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) 
)a
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3