-- 코드를 작성해주세요

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS d
INNER JOIN
(
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)s
ON d.SKILL_CODE & s.CODE = s.CODE 
ORDER BY ID