-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM (
    SELECT a.ITEM_ID, a.ITEM_NAME, a.RARITY, b.PARENT_ITEM_ID
    FROM ITEM_INFO a 
    INNER JOIN ITEM_TREE b
    ON a.ITEM_ID = b.ITEM_ID
) c
INNER JOIN
(
    SELECT DISTINCT a.ITEM_ID AS ITEM_INFO_ID 
    FROM ITEM_INFO a 
    INNER JOIN ITEM_TREE b
    ON a.ITEM_ID = b.PARENT_ITEM_ID
    WHERE a.RARITY = 'RARE'
) d
ON c.PARENT_ITEM_ID = d.ITEM_INFO_ID
ORDER BY ITEM_ID DESC

