-- 코드를 작성해주세요
WITH CTE AS (
    SELECT a.ID, a.GENOTYPE,
    (
        SELECT GENOTYPE
        FROM ECOLI_DATA b
        WHERE a.PARENT_ID = b.ID
    ) AS PARENT_GENOTYPE
    FROM ECOLI_DATA a
)

SELECT *
FROM CTE
WHERE GENOTYPE & PARENT_GENOTYPE = PARENT_GENOTYPE