-- 코드를 작성해주세요
WITH PYTHONCODE AS (
    SELECT CODE AS PYTHON
    FROM SKILLCODES
    WHERE NAME = 'Python'
), CCODE AS (
    SELECT CODE AS C
    FROM SKILLCODES
    WHERE NAME = 'C#'
)

SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM  DEVELOPERS d, PYTHONCODE p, CCODE c
WHERE d.SKILL_CODE & p.PYTHON = p.PYTHON 
    OR d.SKILL_CODE & c.C = c.C
ORDER BY ID