-- 코드를 작성해주세요
SELECT YEAR(a.DIFFERENTIATION_DATE) AS YEAR,
    (
        SELECT MAX(b.SIZE_OF_COLONY)
        FROM ECOLI_DATA b
        WHERE YEAR(b.DIFFERENTIATION_DATE) = YEAR
    ) - a.SIZE_OF_COLONY AS YEAR_DEV,
ID
FROM ECOLI_DATA a
ORDER BY YEAR, YEAR_DEV