-- 코드를 작성해주세요
SELECT (
    SELECT ID
    FROM FISH_INFO fi
    WHERE fi.FISH_TYPE = fn.FISH_TYPE
    ORDER BY fi.LENGTH DESC
    LIMIT 1
) AS ID
, fn.FISH_NAME, (
    SELECT MAX(fi.LENGTH)
    FROM FISH_INFO fi
    WHERE fi.FISH_TYPE = fn.FISH_TYPE
) AS LENGTH
FROM FISH_NAME_INFO fn
ORDER BY ID
