-- 코드를 작성해주세요
WITH CTE AS (
    SELECT *
    FROM DEVELOPERS d
    INNER JOIN SKILLCODES s
    ON d.SKILL_CODE & s.CODE = s.CODE
    WHERE NAME = 'PYTHON' OR NAME = 'C#' OR CATEGORY = 'Front End'
)

SELECT 
    CASE
    WHEN MAX(NAME = 'PYTHON') AND MAX(CATEGORY = 'Front End') THEN 'A'
    WHEN MAX(NAME = 'C#') THEN 'B'
    WHEN MAX(CATEGORY = 'Front End') THEN 'C'
    END AS GRADE,
ID, MAX(EMAIL) AS EMAIL
FROM CTE
GROUP BY ID
HAVING (MAX(NAME = 'PYTHON') AND MAX(CATEGORY = 'Front End')) OR MAX(NAME = 'C#') OR MAX(CATEGORY = 'Front End')
ORDER BY GRADE, ID